# Numpy 
## Sorting
### The function used are 
* numpy.sort()  : This function returns a sorted copy of an array.
* numpy.argsort()  : This function returns the indices that would sort an array.
* numpy.lexsort()  : This function returns an indirect stable sort using a sequence of keys.

Import numpy library and initilise a as array

In [5]:
import numpy as np
a = np.array([9, 3, 1, 7, 4, 3, 6])

**numpy.sort() : This function returns a sorted copy of an array.**

In [2]:
arr1 = np.sort(a, axis = None)        
print ("Array:\n", arr1)

Array:
 [ 1 10 12 15]


**numpy.argsort() : This function returns the indices that would sort an array.**

In [6]:
b = np.argsort(a)
print('Sorted indices:\n', b)

Sorted indices:
 [2 1 5 4 6 3 0]


**To sorted array using sorted indices**

In [7]:
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array:', c)

Sorted array-> [1 3 3 4 6 7 9]


## Searching
### The function used are
* numpy.argmax() : This function returns indices of the max element of the array in a particular axis.
* numpy.nanargmax() : This function returns indices of the max element of the array in a particular axis ignoring NaNs.
* numpy.argmin() : This function returns the indices of the minimum values along an axis.

In [29]:
import numpy as np
array = np.arange(12).reshape(3, 4)

*reshape(x,y)* is a function to give an array the shape of matrix wth 3 *rows* and 4 *columns*

In [9]:
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**numpy.argmax() : This function returns indices of the max element of the array in a particular axis (or as of whole array itself).**
*Indixing in python starts with 0 and not 1*

In [10]:
a = np.argmax(array)
print(a)

11


In [11]:
print(np.argmax(array, axis=0))

[2 2 2 2]


print(np.argmax(array, axis=7))

**If you try running the above code, AxisError is shown** 
which means, there is no axis of 7. It is similar as *Index Error* 
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-14-a81b381532b2> in <module>
----> 1 print(np.argmax(array, axis=7))
      2 

<__array_function__ internals> in argmax(*args, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in argmax(a, axis, out)
   1186 
   1187     """
-> 1188     return _wrapfunc(a, 'argmax', axis=axis, out=out)
   1189 
   1190 

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     56 
     57     try:
---> 58         return bound(*args, **kwds)
     59     except TypeError:
     60         # A TypeError occurs if the object does have such a method in its

AxisError: axis 7 is out of bounds for array of dimension 2

**numpy.nanargmax() : This function returns indices of the max element of the array in a particular axis ignoring NaNs.The results cannot be trusted if a slice contains only NaNs and Infs**

In [30]:
array = [4, 2, 3, 1]
print(array)
print(("Index of maximum array is: "+ str(np.nanargmax(array))))

[4, 2, 3, 1]
Index of maximum array is: 0


**numpy.argmin() : This function returns the indices of the minimum values along an axis.**

In [33]:
print(array)
print("\nIndices of min element : ", np.argmin(array, axis=0))

[4, 2, 3, 1]

Indices of min element :  3


## Counting
### The function used is:
* numpy.count_nonzero() : Counts the number of non-zero values in the array.
    

In [42]:
a =[[0,1,7,0,0],[3,0,0,2,19]]
b =[[0,1,7,0,0],[3,0,0,2,0],[3,0,4,2,45]]
c =np.count_nonzero(a)
d =np.count_nonzero(b)
print("Number of nonzero values is: {}".format(c))
print("Number of nonzero values is: {}".format(d))

Number of nonzero values is: 5
Number of nonzero values is: 8
